disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Shoggoth Industries - Security Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "SHOGGOTH_INDUSTRIES_LogoWithBlackBack.png"
secondaryLogo = "SHOGGOTH_INDUSTRIES_LogoWithWhiteBack.png"
description = "Shoggoth Industries is a simple IOC/IOV provider."
author = { bio = "", headline = "", name = "Shoggoth Industries" }  
