[[main]]
name = "Grafana"
pre  = "grafana"
url = "http://147.93.55.85:3000"
identifier = "agRN9uWdbO"
weight = 9999

[[main]]
name = "OpenCTI"
pre  = "opencti"
url = "http://147.93.55.85:8080"
identifier = "pvGC9jLsqD"
weight = 9999

[[main]]
name = "Database"
pre = "list"
pageRef = "database"
identifier = "6LGCCJwOqr"
weight = 9999

[[main]]
name = "Articles"
pre = "lightbulb"
pageRef = "articles"
identifier = "6YTPPWjBde"
weight = 9999

[[main]]
name = "Daily Reports"
pre = "rss"
pageRef = "daily-posts"
identifier = "ocVC7kT188"
weight = 9999

[[footer]]
none = "none"

[[footer]]
name = "@Shoggoth_Indus"
pre = "bluesky"
url = "https://bsky.app/profile/shoggot-indus.bsky.social"
identifier = "64Rv39iEZy"
weight = 9999

[[footer]]
name = "@Shoggoth_Indus"
pre = "x-twitter"
url = "https://x.com/Shoggoth_Indus"
identifier = "fjfqO7DBs2"
weight = 9999

[[footer]]
name = "Virus Total"
pre  = "virustotal"
url = "https://www.virustotal.com/gui/user/Shoggoth_Industries"
identifier = "ciTP9wYfdQ"
weight = 9999
